@env=dev
@backendUrl = {{$dotenv VITE_BACKEND_URL}}
@alphaVantageApiKey = {{$dotenv ALPHAVANTAGE_API_KEY}}
@polygonApiKey = {{$dotenv VITE_POLYGON_API_KEY}}

POST {{backendUrl}}/users/signup
Content-Type: application/json

{
    "email":"walterWhite@gmail.com","password":"crystalBlue123"
}
###
GET {{backendUrl}}/stocks/AAPL
Content-Type: application/json
Authorization: Bearer 

{
    "ticker":"AAPL"
}
###
GET https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AAPL&apikey={{alphaVantageApiKey}}
Content-Type: application/json

### GET stock
GET {{backendUrl}}/stocks/AAPL
Content-Type: application/json

{
    "ticker":"AAPL"
}
### GET all stock
GET {{backendUrl}}/stocks/
Content-Type: application/json


### GET stock
GET https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=TSLA&apikey={{alphaVantageApiKey}}
Content-Type: application/json


### GETS existing user
POST {{backendUrl}}/users/login
Content-Type: application/json

{
    "email":"walterWhite@gmail.com","password":"crystalBlue123"
}

### create Comment
POST {{backendUrl}}/comments/create
Content-Type: application/json

{
    "ticker":"AAPL", "username":"1", "comment":"example comment"
}
### get Comments
POST {{backendUrl}}/users/getPositions
Content-Type: application/json

{
    "username":"new"
}


### GET
GET https://api.massive.com/v2/aggs/ticker/MSFT/range/1/day/2023-01-09/2023-02-10?adjusted=true&sort=asc&limit=120&apiKey={{polygonApiKey}}
Content-Type: application/json

### GET
GET https://api.massive.com/v3/reference/options/contracts?underlying_ticker=AAPL&limit=50&apiKey={{polygonApiKey}}
Content-Type: application/json
